import "./globals.css";
import { Mulish } from "next/font/google";
import Script from "next/script";
import Header from "@/components/shared/Header";
import Footer from "@/components/shared/Footer";

const mulish = Mulish({
	subsets: ["latin"],
	display: "swap",
	weight: ["200", "300", "300", "400", "500", "600", "700", "800", "900"],
	variable: "--font-mulish",
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body id="body" className={`${mulish.variable} antialiased font-mulish`}>
				<Script src="/bodymovin.js" defer strategy="beforeInteractive" />
				<Header />
				{children}
				<Footer />
			</body>
		</html>
	);
}
